export default [
  { encoding: "f32", property: "positionX" },
  { encoding: "f32", property: "positionY" },
  { encoding: "f32", property: "positionZ" },
  { encoding: "f32", property: "speed" },
  { encoding: "f32", property: "power" },
  { encoding: "f32", property: "torque" },
  { encoding: "f32", property: "tireTempFrontLeft" },
  { encoding: "f32", property: "tireTempFrontRight" },
  { encoding: "f32", property: "tireTempRearLeft" },
  { encoding: "f32", property: "tireTempRearRight" },
  { encoding: "f32", property: "boost" },
  { encoding: "f32", property: "fuel" },
  { encoding: "f32", property: "distanceTraveled" },
  { encoding: "f32", property: "bestLap" },
  { encoding: "f32", property: "lastLap" },
  { encoding: "f32", property: "currentLap" },
  { encoding: "f32", property: "currentRaceTime" },
  { encoding: "u16", property: "lapNumber" },
  { encoding: "u8", property: "racePosition" },
  { encoding: "u8", property: "accel" },
  { encoding: "u8", property: "brake" },
  { encoding: "u8", property: "clutch" },
  { encoding: "u8", property: "handBrake" },
  { encoding: "u8", property: "gear" },
  { encoding: "s8", property: "steer" },
  { encoding: "s8", property: "normalizedDrivingLine" },
] as const;
